version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app             # Sincroniza o código-fonte local com o container
      - /app/node_modules  # Evita conflito entre dependências do host e container
    stdin_open: true
    tty: true
